#!/bin/bash
export MTAF_SITE=vqda1
export MTAF_DB_HOST=vqda1
export HOME=/home/mmccrorey
export MTAF_DIR=$HOME/mtaf
export PYTHONPATH=$MTAF_DIR
export MTAF_LOG_DIR=$MTAF_DIR/log
cd $MTAF_DIR
for scope in select premier office_mgr
do
    CMD="$HOME/virtualenv/new_arch/bin/python $HOME/mtaf/eConsole/run_features.py -f $MTAF_DIR/eConsole/features -p staging -u $scope -r regression"
    echo $(/bin/date) $CMD
    /usr/bin/xvfb-run -e $MTAF_LOG_DIR/xvfb.log -s "-screen 0 1024x768x8" $CMD
    # $CMD
done > $MTAF_LOG_DIR/econsole_regression.log 2>&1
