from .base import base_view
from .login import login_view
from .tnc import tnc_view
from .app_intro import app_intro_view
from .user import user_view
from .contacts import contacts_view
from .history import history_view
from .voicemail import voicemail_view
from .keypad import keypad_view
from .prefs import prefs_view
from .network import network_view
