from .base_view import base_view
from .login_view import login_view
from .tnc_view import tnc_view
from .app_intro_view import app_intro_view
from .user_view import user_view
from .contacts_view import contacts_view
from .history_view import history_view
from .voicemail_view import voicemail_view
from .dial_view import dial_view
from .prefs_view import prefs_view
from .network_view import network_view
from .advanced_settings_view import advanced_settings_view
from .active_call_view import active_call_view
