import lib.mtaf_logging as logging
log = logging.get_logger('mtaf.log_test')
logging.console_handler.setLevel(logging.INFO)
log.debug("debug message")
log.trace("trace message")
log.info("info message")
log.warn("warn message")
# log1 = logging.get_logger('esi.log1')
# log2 = logging.get_logger('esi.log2')
# log1.info("goodbye")
# log2.info("hello")
# logging.set_msg_src('just a test')
# log1.info("world")
# logging.set_msg_src('jat')
# log1.info("goodbye")
# log2.info("goodbye")

