from .base import base_view
from .domain import domain_view
from .domain_auto_attendants import domain_auto_attendants_view
from .domain_call_queues import domain_call_queues_view
from .domain_conferences import domain_conferences_view
from .domain_home import domain_home_view
from .domain_inventory import domain_inventory_view
from .domain_locations import domain_locations_view
from .domain_music_on_hold import domain_music_on_hold_view
from .domain_time_frames import domain_time_frames_view
from .domain_users import domain_users_view
from .domain_home import domain_home_view
from .login import login_view
from .reseller import reseller_view
from .reseller_home import reseller_home_view
from .reseller_domains import reseller_domains_view
from .reseller_inventory import reseller_inventory_view
